name: tiny-rag
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiohttp=3.9.3
  - aiosignal=1.2.0
  - arrow-cpp=14.0.2
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - dataclasses=0.8
  - datasets=2.12.0
  - dill=0.3.6
  - filelock=3.13.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - gflags=2.2.2
  - glog=0.5.0
  - gmpy2=2.1.2
  - grpc-cpp=1.48.2
  - huggingface_hub=0.17.3
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - joblib=1.2.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.5.0
  - libevent=2.1.12
  - libfaiss=1.7.4
  - libffi=3.4.4
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libuv=1.44.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.14
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.7
  - numpy-base=1.26.3
  - openssl=3.0.13
  - orc=1.7.4
  - packaging=23.1
  - pandas=2.1.4
  - pip=23.3.1
  - pyarrow=14.0.2
  - pycparser=2.21
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytorch=2.1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - re2=2022.04.01
  - regex=2023.10.3
  - requests=2.31.0
  - responses=0.13.3
  - sacremoses=0.0.43
  - safetensors=0.4.0
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - tokenizers=0.13.3
  - transformers=4.31.0
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.1.0
  - utf8proc=2.6.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
  - xxhash=0.8.0
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cryptography==42.0.2
      - faiss-cpu==1.7.2
      - numpy==1.26.4
      - pdfminer-six==20231228
      - pillow==10.2.0
      - tqdm==4.66.1
      - ucall==0.5.1
      - openai